name: ios_fl_n_wolftreasury_3369
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2

  logger: ^2.5.0
  share_plus: ^10.1.4
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/
   - assets/images/
   - assets/images/myths/
   - assets/images/places/
   - assets/images/quiz_result/
   - assets/images/onboard/
